Controllers/LibrosController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LibreriaDAIR.Models;

namespace LibreriaDAIR.Controllers
{
    public class LibrosController : Controller
    {
        // GET: Libros
        public ActionResult Index() //
        {
            List<LibroModelo> Libros = new List<LibroModelo>(); //Utilizo una lista para guardar los resultados de los libros

            string string_conexion = ConfigurationManager.ConnectionStrings["conexion"].ConnectionString; //Conección a la base de datos
            string procedimiento_almacenado = "ObtenerLibroxCategoria"; //Procedimiento almacenado

            using (SqlConnection connection = new SqlConnection(string_conexion))
            {
                SqlCommand command = new SqlCommand(procedimiento_almacenado, connection);
                command.CommandType = System.Data.CommandType.StoredProcedure; 

                connection.Open();
                SqlDataReader reader = command.ExecuteReader();

                while (reader.Read())
                {
                    LibroModelo libro = new LibroModelo //Crea un modelo de cada libro con los datos leidos
                    {
                        _idLibro = (int)reader["IdLibro"],
                        _titulo = reader["Titulo"].ToString(),
                        _imagen = reader["Imagen"] != DBNull.Value ? Convert.ToBase64String((byte[])reader["Imagen"]) : null,
                        _precio = reader["Precio"] != DBNull.Value ? Convert.ToDecimal(reader["Precio"]) : 0m
,
                        Categoria = new CategoriaModelo //Crea un modelo para la categoria
                        {
                            _Id = (int)reader["CategoriaId"],
                            _Nombre = reader["CategoriaNombre"].ToString()
                        }
                    };
                    Libros.Add(libro); //Guardo cada modelo libro en la lista
                }
                reader.Close(); 
            }
            return View(Libros);
        }
        //Vista de cada libro con su información
        public ActionResult DetallesLibro(int id) //Es el metodo que mostrará los detalles de cada libro utilizando el id del libro
        {
           LibroModelo libro = ObtenerLibroId(id); //Se llama el metodo que contiene la información del libro
                return View(libro);
        }

        private LibroModelo ObtenerLibroId(int id)
        {
            LibroModelo libro = null;

            string string_conexion = ConfigurationManager.ConnectionStrings["conexion"].ConnectionString;

            using (SqlConnection connection = new SqlConnection(string_conexion))
            {
                connection.Open();
                using (SqlCommand command = new SqlCommand("ObtenerDetalleLibro", connection))
                {
                    command.CommandType = System.Data.CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@IdLibro", id);

                    using (SqlDataReader reader = command.ExecuteReader())//Para leer los datos desde la base
                    {
                        if(reader.Read())//Si se encuentra el libro
                        {
                            libro = new LibroModelo // Se agregan los valores a el modelo libro
                            {
                                _titulo = reader["Titulo"].ToString(),
                                _precio = reader["Precio"] != DBNull.Value ? Convert.ToDecimal(reader["Precio"]) : 0m, 
                                _autor = reader["Autor"].ToString(),
                                _editorial = reader["Editorial"].ToString(),
                                _idioma = reader["Idioma"].ToString(),
                                _numPaginas = (int)reader["NumPaginas"],
                                _imagen = reader["Imagen"] != DBNull.Value ? Convert.ToBase64String((byte[])reader["Imagen"]) : null
                            };
                        }
                    }
                }
            }
                return libro;//Devuelve el modelo
        }
    }
}

Views/Libros/DetallesLibro.cshtml
@model LibreriaDAIR.Models.LibroModelo

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalles del libro</title>
    <link rel="stylesheet" href="~/css/EstiloLibros.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
    <div class="container">
        <header>
            <div class="BarraNavegador">
                <img src="~/Imagenes/LogoDAIR.png" alt="Logo de la app" class="logo">
                <span class="BarraBoton" onclick="Menu()">☰</span>
            </div>
            <nav>
                <ul class="BarraMenu" id="barramenu">
                    <li><a class="Activa" href="/Principal/Index">Inicio</a></li>
                    <li><a href="/Cuenta/Index">Mi cuenta</a></li>
                    <li><a href="/Libros/Index">Categorías</a></li>
                    <li><a href="/Home/Index">Cerrar sesión</a></li>
                </ul>
            </nav>
            <script>
                function Menu() {
                    var menu = document.getElementById('barramenu');
                    menu.classList.toggle('Activa');
                }
            </script>
            <script>
                function CerrarSesionCliente() {
                    if (confirm("¿Desea cerrar la sesión?")) {
                        window.location.href = '/Home/CerrarSesion';
                    }
                }
            </script>
        </header>

        <main>
            <div class="estilo-detalles">
                <img src="data:image/jpeg;base64,@Model._imagen" alt="@Model._titulo" class="imagen-libro" />
                <div class="info-libro">
                    <h3>@Model._titulo</h3>
                    <h4>₡@Model._precio</h4>
                    <p><strong>Autor:</strong> @Model._autor</p>
                    <p><strong>Editorial:</strong> @Model._editorial</p>
                    <p><strong>Idioma: </strong>@Model._idioma</p>
                    <p><strong>Número de páginas:</strong> @Model._numPaginas</p>

                    <form id="formAgregarCarrito" action="/Carrito/AgregarCarrito" method="post">
                        <div class="cantidad-libros">
                            <button type="button" onclick="cambiarCantidad(-1)">-</button>
                            <input type="text" id="cantidad" name="cantidad" value="1" min="1" />
                            <button type="button" onclick="cambiarCantidad(1)">+</button>
                        </div>
                        <input type="hidden" name="titulo" value="@Model._titulo" />
                        <input type="hidden" name="precio" value="@Model._precio" />
                        <button type="submit" class="agregar-carrito">Agregar al carrito</button>
                        <br />
                        <br />
                    </form>

                    <div id="mensajeCarrito" style="display:none; background-color: #d4edda; color: #155724; padding: 10px; border-radius: 5px; margin-top: 20px; margin-bottom: 20px"></div>

                    <a href="@Url.Action("Index", "Libros")" class="custom-link">Volver a categorías</a>
                </div>
            </div>
        </main>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#formAgregarCarrito').submit(function (e) {
                e.preventDefault(); // Evitar que el formulario se envíe de forma tradicional

                // Obtener los datos del formulario
                var formData = $(this).serialize();

                // Realizar la petición AJAX
                $.ajax({
                    url: $(this).attr('action'), // La acción del formulario
                    type: 'POST',
                    data: formData,
                    success: function (response) {
                        // Mostrar el mensaje de éxito
                        $('#mensajeCarrito').text(response.mensaje).fadeIn().delay(3000).fadeOut(); // Mostrar mensaje y ocultarlo después de 3 segundos
                    },
                    error: function () {
                        $('#mensajeCarrito').text('Hubo un error al agregar el libro al carrito.').fadeIn().delay(3000).fadeOut();
                    }
                });
            });
        });
    </script>
    <footer>
        <nav>
            <ul>
                <li><a href="/Principal/Index"><i class="fas fa-home"></i></a></li>
                <li><a href="/Carrito/Index"><i class="fas fa-shopping-cart"></i></a></li>
            </ul>
        </nav>
    </footer>
    <script>
        function cambiarCantidad(cambio) {
            const cantidadInput = document.getElementById('cantidad');
            let cantidad = parseInt(cantidadInput.value);
            cantidad += cambio;
            if (cantidad < 1) cantidad = 1; // Mantener mínimo en 1
            cantidadInput.value = cantidad;
        }
    </script>
</body>
</html>

Views/Libros/Index.cshtml
@model List<LibreriaDAIR.Models.LibroModelo>

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Categorias</title>
    <link rel="stylesheet" href="~/css/EstiloCategorias.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
    <div class="container">
        <header>
            <div class="BarraNavegador">
                <img src="~/Imagenes/LogoDAIR.png" alt="Logo de la app" class="logo">
                <span class="BarraBoton" onclick="Menu()">☰</span>
            </div>
            <nav>
                <ul class="BarraMenu" id="barramenu">
                    <li><a class="Activa" href="/Principal/Index">Inicio</a></li>
                    <li><a href="/Cuenta/Index">Mi cuenta</a></li>
                    <li><a href="/Libros/Index">Categorías</a></li>
                    <li><a href="/Home/Index">Cerrar sesión</a></li>
                </ul>
            </nav>
            <script>
                function Menu() {
                    var menu = document.getElementById('barramenu');
                    menu.classList.toggle('Activa');
                }
            </script>
            <script>
                function CerrarSesionCliente() {
                    if (confirm("¿Desea cerrar la sesión?")) {
                        window.location.href = '/Home/CerrarSesion';
                    }
                }
            </script>
        </header>

        @functions {
            public string ObtenerImagenCategoria(string categoria)
            {
                switch (categoria)
                {
                    case "Libros infantiles":
                        return Url.Content("~/Imagenes/LibrosInfantiles.png");
                    case "Fantasía":
                        return Url.Content("~/Imagenes/LibrosFantasia.png");
                    case "Romance":
                        return Url.Content("~/Imagenes/LibrosRomance.png");
                    case "Novela Gráfica":
                        return Url.Content("~/Imagenes/LibrosNovelaGrafica.jpg");
                    default:
                        return Url.Content("~/Imagenes/DefaultCategoria.png"); // Imagen por defecto
                }
            }
        }

        <main class="Libros">
            <h2>Categorías</h2>

            @if (Model != null && Model.Any()) // Verifica si el modelo no es null y tiene libros
            {
                // Agrupamos los libros por categoría
                var categorias = Model.GroupBy(l => l.Categoria._Nombre);

                <!-- Contenedor para las categorías -->
                <div class="categorias-container">
                    @foreach (var categoria in categorias)
                    {
                        <div class="categoria-tarjeta" onclick="mostrarLibrosPorCategoria('@categoria.Key')">
                            <img src="@ObtenerImagenCategoria(categoria.Key)" alt="@categoria.Key" class="categoria-img" />
                            <h3 class="categoria-titulo">@categoria.Key</h3>
                        </div>
                    }
                </div>

                <!-- Contenedor para mostrar libros -->
                <div id="contenedorLibros">
                    @foreach (var categoria in categorias)
                    {
                        <section id="categoria-@categoria.Key" style="display: none;">
                            <div class="LibrosTarjetas">
                                @foreach (var libro in categoria)
                                {
                                    <div class="tarjeta">
                                        <a style="text-decoration: none;" href="@Url.Action("DetallesLibro", "Libros", new { id = libro._idLibro })">
                                            <img src="data:image/jpeg;base64,@libro._imagen" alt="@libro._titulo" />
                                            <div class="informacion">
                                                <p>@libro._titulo</p>
                                                <p>₡@libro._precio</p>
                                            </div>
                                        </a>
                                    </div>
                                }
                            </div>
                        </section>
                    }
                </div>
            }
            else
            {
                <p>No hay libros disponibles.</p>
            }

            <script>
                // Función para mostrar libros según la categoría seleccionada
                function mostrarLibrosPorCategoria(categoria) {
                    // Ocultar todas las secciones de libros
                    const secciones = document.querySelectorAll('section[id^="categoria-"]');
                    secciones.forEach(seccion => seccion.style.display = 'none');

                    // Mostrar la sección de la categoría seleccionada
                    const seccionSeleccionada = document.getElementById('categoria-' + categoria);
                    if (seccionSeleccionada) {
                        seccionSeleccionada.style.display = 'block';
                    }
                }
            </script>
        </main>
    </div>
    <footer>
        <nav>
            <ul>
                <li><a href="/Principal/Index"><i class="fas fa-home"></i></a></li>
                <li><a href="/Carrito/Index"><i class="fas fa-shopping-cart"></i></a></li>
            </ul>
        </nav>
    </footer>
</body>
</html>